### ISSUE TITLE
does it has md5 hash ?

### ISSUE THREAD

**Issue by vatheara** [ishinvin/ts-khqr#2]
because in [official SDK Document](https://bakong.nbc.gov.kh/download/KHQR/integration/KHQR%20SDK%20Document.pdf)
I saw the result of other language contain md5 property in there.

![image](https://github.com/ishinvin/ts-khqr/assets/18604920/80f26554-73dc-4b13-9058-13348804c593)

and your ReturnType doesn't have md5 hash string property. 

![image](https://github.com/ishinvin/ts-khqr/assets/18604920/ea05763c-5d9e-4061-b899-84ef23de3b8a)

the reason I open this issue because I want to implement **check transaction status** .

**Comment by ishinvin** [comment]
Updated in version 2.1.0
Cheers!
