### ISSUE TITLE
Inconsistent Result of KHQR.generate method

### ISSUE THREAD

**Issue by horkimsereirith** [ishinvin/ts-khqr#3]
While using [bakong-khqr](https://www.npmjs.com/package/bakong-khqr), response of `generateIndividual` returns `qr` and `md5`. Then why this version only return `qr` data.

- Javascript package response
```json
{
    "status": {
        "code": 0,
        "errorCode": null,
        "message": null
    },
    "data": {
        "qr": "00020101021229460015jonh_smith@devb0111855122334550208DevBank5204599953038405406100.505802KH5910JonhSmith6010PHNOMPENH62430211855122334550311CoffeeShop0709Cashier_199170013163115460356263048065",
        "md5": "f5a7dca43bcda57276d4fb175c17fd51"
    }
}
```

- Ts package response
```json
{
    "status": {
        "code": 0,
        "errorCode": null,
        "message": null
    },
    "data": "00020101021229460015jonh_smith@devb0111855122334550208DevBank5204599953038405406100.505802KH5910JonhSmith6010PHNOMPENH62430211855122334550311CoffeeShop0709Cashier_199170013163115460356263048065"
}
```

![image](https://github.com/ishinvin/ts-khqr/assets/58946504/114c54ad-ae31-421a-aab4-546608c7a709)

**Later I found that the js version only hash using md5 library on return statement. It would be nice if this ts version return the same result. :)**

**Comment by ishinvin** [comment]
Updated in version 2.1.0
Cheers!
